version: "3.9"
services:
  mysql:
    image: mysql:8.4
    container_name: iia-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=iia
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4-alpine
    container_name: iia-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
    driver: local
    name: iia-mysql-data